import torch
import numpy as np
import monai.transforms as mt

def test_standalone_transform():
    print("[*] Initializing MONAI RandAffined...")
    gpu_transform_fn = mt.RandAffined(
        keys=["data", "seg"],
        prob=1.0,  # force apply for testing
        rotate_range=(np.pi/12, np.pi/12, np.pi/12),
        scale_range=(0.1, 0.1, 0.1),
        mode=["bilinear", "nearest"],
        padding_mode="zeros"
    )

    # Let's simulate a batch generated by the DataLoader (shape [B, C, H, W, D])
    # with batch_size = 1
    print("\n--- TEST BATCH SIZE = 1 ---")
    batch = {
        "data": torch.randn(1, 4, 32, 32, 32),
        "seg": torch.randint(0, 4, (1, 1, 32, 32, 32)).float()
    }
    print("Original Batch shapes:")
    print("  - data:", batch["data"].shape)
    print("  - seg:", batch["seg"].shape)

    # Apply our new batch processing logic
    try:
        any_key = next(iter(gpu_transform_fn.keys))
        batch_size = batch[any_key].shape[0]
        
        if batch_size == 1:
            squeezed_batch = {
                k: v.squeeze(0) if isinstance(v, torch.Tensor) else v
                for k, v in batch.items()
            }
            print("Squeezed shapes for MONAI:")
            print("  - data:", squeezed_batch["data"].shape)
            print("  - seg:", squeezed_batch["seg"].shape)
            
            transformed = gpu_transform_fn(squeezed_batch)
            print("[+] Transform successful!")
            
            batch = {
                k: v.unsqueeze(0) if isinstance(v, torch.Tensor) else v
                for k, v in transformed.items()
            }
            print("Restored Batch shapes:")
            print("  - data:", batch["data"].shape)
            print("  - seg:", batch["seg"].shape)
            
    except Exception as e:
        print("[!] FAILED batch_size=1:")
        import traceback
        traceback.print_exc()

    # Let's simulate batch_size = 2
    print("\n--- TEST BATCH SIZE = 2 ---")
    batch = {
        "data": torch.randn(2, 4, 32, 32, 32),
        "seg": torch.randint(0, 4, (2, 1, 32, 32, 32)).float()
    }
    print("Original Batch shapes:")
    print("  - data:", batch["data"].shape)
    print("  - seg:", batch["seg"].shape)

    try:
        any_key = next(iter(gpu_transform_fn.keys))
        batch_size = batch[any_key].shape[0]
        
        if batch_size == 1:
            pass
        else:
            samples = []
            for i in range(batch_size):
                sample = {
                    k: v[i] if isinstance(v, torch.Tensor) else v
                    for k, v in batch.items()
                }
                samples.append(gpu_transform_fn(sample))
            
            batch = {}
            for k in samples[0].keys():
                if isinstance(samples[0][k], torch.Tensor):
                    batch[k] = torch.stack([s[k] for s in samples], dim=0)
                else:
                    batch[k] = samples[0][k]
                    
            print("[+] Transform successful for batch_size = 2!")
            print("Restored Batch shapes:")
            print("  - data:", batch["data"].shape)
            print("  - seg:", batch["seg"].shape)
            
    except Exception as e:
        print("[!] FAILED batch_size=2:")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    test_standalone_transform()
